name: Node Crawler & Deploy

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  crawl-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install Dependencies
      run: |
        pip install --upgrade requests pyyaml tenacity
        npm install -g wrangler@latest

    - name: Run Crawler
      env:
        CRAWLER_GITHUB_TOKEN: ${{ secrets.CRAWLER_GITHUB_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      run: python main.py

    - name: Deploy to Cloudflare
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      run: |
        # 检查部署目录
        echo "部署目录内容:"
        ls -la output/cloudflare
        
        # 进入目录部署
        cd output/cloudflare
        wrangler pages deploy . --project-name=node-subscription --branch=main
